# Generated by Django 5.1.4 on 2024-12-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_travelpackage_destination_travelpackage_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
