# Generated by Django 5.1.4 on 2024-12-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_travelpackage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='tags',
            field=models.CharField(choices=[('Family', 'Family Trip'), ('Adventure', 'Adventure'), ('Romantic', 'Romantic Getaway'), ('Business', 'Business Trip')], default='Family', max_length=20),
        ),
    ]
